# Docker Compose for Trimix Analyzer Production

services:
  trimix-analyzer:
    image: ghcr.io/magnus188/trimix-analysator:latest
    # Fallback to local build if image not available
    build:
      context: .
    container_name: trimix-analyzer
    restart: unless-stopped  # Auto-restart for production
    privileged: true
    network_mode: host
    devices:
      - "/dev/i2c-1:/dev/i2c-1"    # I2C bus for sensors
      - "/dev/gpiomem:/dev/gpiomem" # GPIO access for power button
      - "/dev/fb0:/dev/fb0"        # Framebuffer for display
      - "/dev/input:/dev/input"    # Input devices for touchscreen
      - "/dev/tty0:/dev/tty0"      # Console access
      - "/dev/tty1:/dev/tty1"      # Console access
    volumes:
      - /sys:/sys:ro                # GPIO sysfs access
      - ./data:/app/data           # Persistent data storage
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 socket
      - /dev/shm:/dev/shm          # Shared memory
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Docker socket for updates
    environment:
      - TRIMIX_ENVIRONMENT=production
      - TRIMIX_MOCK_SENSORS=0
      - TRIMIX_AUTO_UPDATE=false   # Control auto-updates
      # Performance-optimized graphics environment variables
      - KIVY_WINDOW=sdl2
      - KIVY_GL_BACKEND=gl
      - KIVY_DPI=96
      - KIVY_METRICS_DENSITY=1
      # Try hardware acceleration first
      - LIBGL_ALWAYS_INDIRECT=0
      - MESA_GL_VERSION_OVERRIDE=3.3
      - GALLIUM_DRIVER=llvmpipe  # Better software fallback than softpipe
      # Memory and I/O optimizations
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # Disable unnecessary graphics warnings
      - KIVY_NO_CONSOLELOG=1
    # Resource limits for consistent performance
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2.0'
        reservations:
          memory: 256M
          cpus: '1.0'
    # Performance optimizations
    shm_size: 128mb  # Increased shared memory for graphics
    tmpfs:
      - /tmp:size=100m,noatime
      - /var/tmp:size=50m,noatime
    working_dir: /app
    command: python main.py
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
  # Optional: monitoring container
  watchtower:
    image: containrrr/watchtower
    container_name: trimix-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    profiles:
      - monitoring
