# Docker Compose for Development - Simple GUI setup

services:
  trimix-dev:
    build:
      context: .
    container_name: trimix-dev
    restart: "no"
    privileged: true
    network_mode: host
    devices:
      - "/dev/i2c-1:/dev/i2c-1"    # I2C bus for sensors
      - "/dev/gpiomem:/dev/gpiomem" # GPIO access for power button
      - "/dev/fb0:/dev/fb0"        # Framebuffer for display
      - "/dev/input:/dev/input"    # Input devices for touchscreen
      - "/dev/tty0:/dev/tty0"      # Console access
      - "/dev/tty1:/dev/tty1"      # Console access
    volumes:
      - /sys:/sys:ro                # GPIO sysfs access
      - .:/app                      # Live code mounting for development
      - ./data:/app/data           # Persistent data storage
      - /dev/shm:/dev/shm          # Shared memory
    environment:
      - TRIMIX_ENVIRONMENT=development
      - TRIMIX_MOCK_SENSORS=1
      # Performance optimizations for development
      - KIVY_WINDOW=sdl2
      - KIVY_GL_BACKEND=gl
      - KIVY_DPI=96
      - KIVY_METRICS_DENSITY=1
      - LIBGL_ALWAYS_INDIRECT=0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # Resource limits to prevent resource starvation
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    # Performance optimizations
    shm_size: 128mb
    tmpfs:
      - /tmp:size=100m,noatime
    working_dir: /app
    command: python main.py
    stdin_open: true
    tty: true

  # For testing only (no GUI)
  trimix-test:
    build:
      context: .
    container_name: trimix-test
    restart: "no"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - TRIMIX_ENVIRONMENT=development
      - TRIMIX_MOCK_SENSORS=1
    working_dir: /app
    command: python -m pytest tests/ -v
    stdin_open: true
    tty: true

  # For interactive development/debugging
  trimix-shell:
    build:
      context: .
    container_name: trimix-shell
    restart: "no"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - TRIMIX_ENVIRONMENT=development
      - TRIMIX_MOCK_SENSORS=1
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
