"""Read-only saved-contour review of CE-only candidate; no PCB or CAD mutation."""
from pathlib import Path
import importlib.util,json,hashlib
D=Path(__file__).resolve().parent;O=D/'ce-ground-review';O.mkdir(exist_ok=True)
module=D.parent/'cap-signal-reconnect/pullup-swap/independent-ground/audit_ground.py'
spec=importlib.util.spec_from_file_location('ce_ground_shared',module);a=importlib.util.module_from_spec(spec);spec.loader.exec_module(a);a.OUT=O
a.COLORS['/01  CHARGING + BATTERY/CHG_CE_N']='#1358be';a.COLORS['USB_OVP_SET']='#d59d13';a.COLORS['USB_CC_INT_N']='#9445a3'
paths=[D/'before.kicad_pcb',D/'ce-bridge-scout/candidate/Trimix_Analyzer.kicad_pcb'];hs=['609a6241ce50cbe3d40f7a1676c455092db583875895eeb8236083bf2c5f0ef1','3ba04d481d49b39d87a800c941448d665bcbd465af761bb2b0d617c23429b469'];assert [a.sha(p)for p in paths]==hs
b,c=[a.load(p)for p in paths];out={'status':'READ_ONLY_GEOMETRY_REVIEW','source_sha256':hs[0],'candidate_sha256':hs[1],'script_sha256':a.sha(Path(__file__)),'shared_geometry_script_sha256':a.sha(module),'method':'Saved filled contours minus drilled openings; positive annular contacts. Circle approximations128segments/quadrant; not thermal/EMC/current rating. No PCB mutation.','layers':{},'anchors':{'source':a.anchor_witnesses(b),'candidate':a.anchor_witnesses(c)},'release':False}
for L in ['In1.Cu','In2.Cu']:
 B,C=b['fills'][L],c['fills'][L]
 out['layers'][L]={'source_saved_area_mm2':B.area,'candidate_saved_area_mm2':C.area,'removed_saved_area_mm2':B.difference(C).area,'added_saved_area_mm2':C.difference(B).area,'source_regions':a.components(b,L),'candidate_regions':a.components(c,L)}
oldcontacts={L:{v['uuid']for v in out['anchors']['source']if v['layers'][L]['contact']}for L in ['In1.Cu','In2.Cu']};newcontacts={L:{v['uuid']for v in out['anchors']['candidate']if v['layers'][L]['contact']}for L in oldcontacts}
out['local_via_throats'],lines=a.throat_review(b,c,[6.4,88.35]);out['gates']={'same_zone_outlines_settings':a.zone_definitions(b['native'])==a.zone_definitions(c['native']),'all_GND_contacts_preserved':oldcontacts==newcontacts,'In1_one_region':len(a.polys(c['physical']['In1.Cu']))==1,'In1_no_signal_tracks':not[t for t in c['native'].tracks if t['layer']=='In1.Cu'and t['net']!='GND'],'all_In2_regions_anchor_to_In1':all(x['has_anchor_to_In1']for x in out['layers']['In2.Cu']['candidate_regions'])}
out['renders']=[a.view('local-planes',[(b,'In1.Cu','BEFORE In1','anchors'),(c,'In1.Cu','CE CANDIDATE In1','anchors'),(b,'In2.Cu','BEFORE In2','anchors'),(c,'In2.Cu','CE CANDIDATE In2','anchors')],(2,83,15,94.3),'Actual saved fill; CE blue; contacts use GND annuli. Only CE detour is present; SYS remains unrouted.',2200),a.view('outer-layer-overlays',[(b,'F.Cu','BEFORE F.Cu','normal'),(c,'F.Cu','CE CANDIDATE F.Cu','normal'),(b,'B.Cu','BEFORE B.Cu','normal'),(c,'B.Cu','CE CANDIDATE B.Cu','normal')],(2,83,15,94.3),'Actual outer-layer copper and pads. The new CE B.Cu diagonal is blue; purchased poses fixed.',2200),a.view('local-via-throats',[(b,'In1.Cu','BEFORE In1','normal'),(c,'In1.Cu','NEW VIA In1','throats')],(4.4,86.35,8.4,90.35),'Local saved-polygon material witnesses near CE via6.4,88.35; not a global neck/current claim.',2000,lines)]
assert [a.sha(p)for p in paths]==hs
(O/'review.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'gates':out['gates'],'layers':{L:{k:v for k,v in r.items()if not k.endswith('regions')}for L,r in out['layers'].items()},'anchor_counts':{L:len(s)for L,s in newcontacts.items()}},indent=2))
