#:kivy 2.0.0

<SettingsButton>:
    text: root.title
    font_size: '24sp'
    size_hint_y: None
    height: dp(80)
    color: 1, 1, 1, 1
    background_color: 0, 0, 0, 0  # Make default background transparent
    
    canvas.before:
        Color:
            rgba: root.background_color_custom
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(8),]
