"""Bind completed independent checks and manually inspected images; no source mutations."""
from pathlib import Path
import hashlib,json,datetime
D=Path(__file__).resolve().parent;ROOT=Path.cwd();P=D.parent;BASE=ROOT/'hardware/system-review/electrical/routing-candidate/sensitive-layout-refinement/frozen-local-bundle'
B=BASE/'hardware/pcb/analyzer/Trimix_Analyzer.kicad_pcb';XML=BASE/'review/analyzer-netlist.xml'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
rel=lambda p:str(p.relative_to(ROOT))
rec=lambda p:dict(path=rel(p),sha256=sha(p))
assert sha(B)=='0962ad86f9834ce71b6439d0f95db603753801153490e78f387a88521e582788'
manifest=BASE/'review/cam-input-manifest.json';supp=BASE/'review/supplementary-drawings-manifest.json'
for m in [manifest,supp]:
 data=json.loads(m.read_text());assert all(sha(BASE/q['path'])==q['sha256']for q in data['files'])
a=json.loads((D/'audit.json').read_text());l=json.loads((D/'assembly-ledger-audit.json').read_text());p=json.loads((D/'process-audit.json').read_text());r=json.loads((D/'refinement-preservation-audit.json').read_text())
assert(a['passed'],a['failed'],l['passed'],l['failed'],p['passed'],p['failed'],r['passed'],r['failed'])==(44,0,20,0,50,1,12,0)
assert [c for c in p['checks']if not c['passed']][0]['category']=='factory-approval-hold'
baseargs=['--board',rel(B),'--cam',rel(BASE/'cam'),'--out',rel(D)];py='/tmp/trimix-gerbonara-venv/bin/python';expected=['--expected-sha256',sha(B)]
commands=[dict(argv=[py,rel(P/'audit_exports.py'),*baseargs,'--netlist',rel(XML),'--bom',rel(BASE/'cam/assembly-reference-map.csv')],exit_code=0),dict(argv=[py,rel(P/'audit_assembly_ledgers.py'),*baseargs,*expected],exit_code=0),dict(argv=[py,rel(P/'audit_final_process.py'),*baseargs,*expected,'--factory-cam',rel(BASE/'factory-stencil'),'--fill-cap-table',rel(BASE/'fill-cap-process/required-fill-cap-holes.csv')],exit_code=1,note='Expected external supplier fill/cap approval hold only'),dict(argv=[py,rel(D/'audit_refinement_preservation.py')],exit_code=0),dict(argv=[py,rel(D/'render_remaining_cam.py')],exit_code=0)]
images=['F-Cu.png','B-Cu.png','In1-Cu.png','In2-Cu.png','U115-copper-paste.png','U201-copper-paste.png',*json.loads((D/'rendered-cam-files.json').read_text())['outputs']]
assert set(images)=={q.name for q in D.glob('*.png')}
suppimages=[rel(BASE/q['path'])for q in json.loads(supp.read_text())['files']if q['path'].endswith('.png')]
receipt={'schema':2,'completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'INDEPENDENT_EXPORT_AND_CONNECTIVITY_PASS_FACTORY_PROCESS_APPROVAL_PENDING','board_sha256':sha(B),'netlist_sha256':sha(XML),'source_bundle':rel(BASE),'owner_cam_manifest':{**rec(manifest),'files':36,'all_hashes_verified_before_and_after':True},'supplementary_drawings_manifest':{**rec(supp),'files':11,'all_hashes_verified':True},'general_checks':{'passed':44,'failed':0},'assembly_ledger_checks':{'passed':20,'failed':0},'refinement_preservation_checks':{'passed':12,'failed':0},'process_checks':{'passed':50,'unfulfilled_external_factory_approval_holds':1,'other_failures':0},'runtime':a['runtime'],'counts':a['counts'],'open_nets':len(a['open_nets']),'shorts':0,'assembly_quantities':{'factory':27,'manual':118,'DNP':6,'PCB_features':18,'total_refs':169,'populated_purchasing_parts':145,'visible_native_references':141,'assembly_map_only_references':28},'fill_cap_holes':{'package_thermal':24,'routed_signal':3,'total':27,'thermal_bores_overlapping_factory_paste':12,'table':rec(BASE/'fill-cap-process/required-fill-cap-holes.csv'),'supplier_accepted':False},'commands':commands,'scripts':[rec(q)for q in [P/'audit_exports.py',P/'cam_geometry.py',P/'audit_final_process.py',P/'final-process-contract.json',P/'audit_assembly_ledgers.py',P/'requirements.lock.txt',D/'audit_refinement_preservation.py',D/'render_remaining_cam.py',D/'build_receipt.py']],'review_outputs':[rec(q)for q in sorted(D.iterdir())if q.is_file()and q.name not in ['verification-receipt.json','receipt-build.log']],'visual_review':{'inspected':images,'supplementary_inspected':suppimages,'finding':'No new export discrepancy; selected exact lands and factory-only paste confirmed. Masked VIPPO and package thermal holes retain the specified process hold. Bottom views use top coordinates.'},'limitations':['Supplier fill/cap, flatness, voiding, drilling, stencil and assembly approval are pending.','No generic open via is authorized under a populated paste aperture; C706 DNP paste is excluded from the factory stencil.','Native and export geometry do not prove analogue accuracy, sensor performance, transient survival, cold-start behaviour, load or thermal capacity, physical assembly or enclosure fit.','Root separately owns final power-path, reference-plane, hardware contract and Fusion evidence.','No fabrication upload, purchase, board mutation or physical test occurred.'],'order_release':False}
(D/'verification-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
print('RECEIPT',sha(D/'verification-receipt.json'));print('BOARD',sha(B));print('XML',sha(XML));print('PASSED',44+20+50+12,'EXTERNAL_HOLDS',1,'IMAGES',len(images),'SUPPLEMENTARY',len(suppimages))
